CREATE TABLE darisetti.activities (
  activityid VARCHAR2(40 BYTE) NOT NULL,
  activitycode NUMBER(10),
  scheduledby VARCHAR2(20 BYTE),
  byperson VARCHAR2(20 BYTE),
  bydate DATE,
  completiondate DATE,
  completionby VARCHAR2(20 BYTE),
  status VARCHAR2(15 BYTE),
  username VARCHAR2(20 BYTE),
  usertimestamp DATE,
  uploaduser VARCHAR2(20 BYTE),
  uploadtime DATE,
  prioritycode NUMBER(10),
  activityresult NUMBER(10),
  isreinquiry VARCHAR2(1 BYTE),
  bytime VARCHAR2(15 BYTE),
  completedtime VARCHAR2(15 BYTE),
  linkid VARCHAR2(41 BYTE),
  linktype VARCHAR2(40 BYTE),
  primarylinkid VARCHAR2(41 BYTE),
  seqno NUMBER,
  createdby VARCHAR2(20 BYTE),
  createddate DATE,
  modifiedby VARCHAR2(20 BYTE),
  modifieddate DATE,
  deletedby VARCHAR2(20 BYTE),
  deleteddate DATE,
  addtocalender VARCHAR2(2 BYTE),
  PRIMARY KEY (activityid)
);